RfqEbr/1.UserInterface/EBR.Web/Controllers/Stock/StockDeviceITController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EBR.Web.Helpers;
using EBR.Web.Models;
using RfqEbr.Data.Contracts;

namespace EBR.Web.Controllers
{
    public class StockDeviceITController : Controller
    {
        private readonly IUnitOfWork _uow;

        public StockDeviceITController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        // Return View To StockDeviceIT.cshtml
        public ActionResult ViewStockDeviceIT(int EmpNo, string CodeId)
        {
            int empSession = Convert.ToInt32(Session["EmpNo"]);

            if (empSession != EmpNo)
            {
                return RedirectToAction("Login", "Home");
            }

            var CheckRole = _uow.YMTGUsers.GetAll().Where(t => t.Id == EmpNo).FirstOrDefault();

            if (EmpNo == 0)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                if (CheckRole.Status == "0" || CheckRole.Status == "2" || CheckRole.Status == "33")
                {
                    var EmpUser = new UserQuo
                    {
                        EmpNo = EmpNo,
                        CodeId = CodeId
                    };
                    return View("~/Views/Home/StockDevice_IT/StockDeviceIT.cshtml", EmpUser);
                }
                else
                {
                    return RedirectToAction("Home", "Home", new { EmpNo = EmpNo });
                }
            }
        }

        // ReceiveStockIT
        // Return View To ReceiveStockIT.cshtml
        public ActionResult ViewReceiveStockIT(int EmpNo, string CodeId)
        {
            int empSession = Convert.ToInt32(Session["EmpNo"]);

            if (empSession != EmpNo)
            {
                return RedirectToAction("Login", "Home");
            }

            var CheckRole = _uow.YMTGUsers.GetAll().Where(t => t.Id == EmpNo).FirstOrDefault();

            if (EmpNo == 0)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                if (CheckRole.Status == "0" || CheckRole.Status == "2" || CheckRole.Status == "33")
                {
                    var EmpUser = new UserQuo
                    {
                        EmpNo = EmpNo,
                        CodeId = CodeId
                    };
                    return View("~/Views/Home/StockDevice_IT/Receive/ReceiveStockIT.cshtml", EmpUser);
                }
                else
                {
                    return RedirectToAction("Home", "Home", new { EmpNo = EmpNo });
                }
            }
        }

        // API to get data with paging
        public ActionResult GetStockData()
        {
            var totalItems = _uow.StockDeviceITs.GetAll().Count();
            var GETDATA = _uow.StockDeviceITs.GetAll()
                            .OrderBy(u => u.Code)
                            .ToList();

            var result = new
            {
                items = GETDATA,
                totalPages = (int)Math.Ceiling((double)totalItems / 10)
            };

            return new JsonNetResult(result);
        }
    }
}

RfqEbr/1.UserInterface/EBR.Web/Views/Shared/Profile2.cshtml
@using EBR.Web.Services
@{
    var pathImages = Url.Content("~/Images/");
}

@model int

    <li class="nav-item dropdown" ng-controller="mainController" ng-init="MRBDataName(@Model)">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fa fa-bell-o"></i>
                <span class="nav-header">{{emplist.EmpNo}} : {{emplist.EmpNameEng}}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header text-center text-bold">Welcome To </span>
                <div class="dropdown-divider"></div>
                <div class="card-body">
                    <div class="text-center">
                        <div class="text-center">

                            <img class="profile-user-img img-fluid img-circle"
                                 src="~/Scripts/admin-lte3/dist/img/avatar.png"
                                 alt="User profile picture">
                        </div>
                        <p class="text-muted text-center p-3"><b>{{emplist.PositionName}}</b></p>
                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b>EmpNo :</b>
                                <label>{{emplist.EmpNo}}</label>
                            </li>
                            <li class="list-group-item">
                                <b class="text-left">Department</b>
                                <p>{{emplist.SectionName}}</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
    </li>
        
        <li class="nav-item">
            @using (Html.BeginForm("LogOff", "Home"))
            {
                <button class="btn btn-info btn-xs " type="submit"><i class="fa fa-sign-out"></i>&nbsp;Logoff</button>
            }
        </li>
   

RfqEbr/1.UserInterface/EBR.Web/Views/Shared/_LayoutHOMEData.cshtml
@model EBR.Web.Models.UserQuo
@using EBR.Web.Services
@{
    var pathImages = Url.Content("~/Images/");
    var parthIcon = pathImages + "PraIcon.ico";
    var baseurl = Request.Url.GetLeftPart(UriPartial.Authority) + Url.Content("~");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="X-UA-Compatible" content="IE=10; IE=9; IE=8; IE=7; IE=EDGE" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes">
    <title>YMT-GROUP</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <link rel="shortcut icon" href="~/Images/YMTHolding.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.25/dist/sweetalert2.min.css">
    <link href="~/Styles/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Styles/assets/css/app.min.css" rel="stylesheet" type="text/css" id="app-style" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></script>
    <script src="~/Scripts/Quagga.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/simplebar@latest/dist/simplebar.min.css">
    <script src="https://unpkg.com/simplebar@latest/dist/simplebar.min.js"></script>

    <style>
        #leftside-menu-container {
            max-height: calc(100vh - 150px); /* ปรับความสูงให้เมนูเลื่อนเมื่อเกินขอบเขต */
            overflow-y: auto;
        }
    </style>

</head>
<body class="loading" data-layout-color="light" data-leftbar-theme="dark" data-layout-mode="fluid" data-rightbar-onstart="true" ng-app="MainApp" ng-controller="mainController">
    <div class="wrapper" id="app">
        <div class="leftside-menu">
            <a href="@Url.Action("YMTHome", "Home")?EmpNo=@Model.EmpNo&CodeId=@Model.CodeId" class="logo text-center logo-light" >
                <span class="logo-lg">
                    <img src="~/Images/YMTHolding.png" alt="" height="150" />
                </span>
                <span class="logo-sm">
                    <img src="~/Images/YMTHolding.png" alt="" height="50" />
                </span>
            </a>

            <div class="mt-5" id="leftside-menu-container" data-simplebar>
                <ul class="side-nav">
                    <li class="side-nav-title side-nav-item"></li>
                    <li class="side-nav-title side-nav-item">MenuApps</li>
                    <li class="side-nav-item">
                        <a href="#" class="side-nav-link">
                            <i class="uil-schedule"></i>
                            <span> Management </span>
                        </a>
                    </li>
                    <li class="side-nav-item">
                        <a data-bs-toggle="collapse" href="#sidebarNds" aria-expanded="false" aria-controls="sidebarNds" class="side-nav-link">
                            <i class="uil-shopping-trolley"></i>
                            <span class="badge bg-danger text-white float-end">New</span>
                            <span> NDS System </span>
                        </a>
                        <div class="collapse" id="sidebarNds">
                            <ul class="side-nav-second-level">
                                <li>
                                    <a href="#">Dashboard</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("YMTNdsSystem", "Home")?EmpNo=@Model.EmpNo&CodeId=@Model.CodeId">NDS-System</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="side-nav-item">
                        <a data-bs-toggle="collapse" href="#sidebarCrms" aria-expanded="false" aria-controls="sidebarCrms" class="side-nav-link">
                            <i class="uil-shopping-basket"></i>
                            <span class="badge bg-danger text-white float-end">New</span>
                            <span> NDS SHOP </span>
                        </a>
                        <div class="collapse" id="sidebarCrms">
                            <ul class="side-nav-second-level">
                                <li>
                                    <a href="#">Dashboard</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("YMTNdsStock", "Home")?EmpNo=@Model.EmpNo&CodeId=@Model.CodeId">NDS-STOCK</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="side-nav-item">
                        <a data-bs-toggle="collapse" href="#sidebarC" aria-expanded="false" aria-controls="sidebarC" class="side-nav-link">
                            <i class="uil-shopping-cart-alt"></i>
                            <span class="badge bg-danger text-white float-end">New</span>
                            <span> Holiday SHOP </span>
                        </a>
                        <div class="collapse" id="sidebarC">
                            <ul class="side-nav-second-level">
                                <li>
                                    <a href="#">Dashboard</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("NDSHolidayStock", "Home")?EmpNo=@Model.EmpNo&CodeId=@Model.CodeId">Holiday STOCK</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="side-nav-item">
                        <a data-bs-toggle="collapse" href="#sidebarProjects" aria-expanded="false" aria-controls="sidebarProjects" class="side-nav-link">
                            <i class="uil-desktop"></i>
                            <span> IT </span>
                            <span class="menu-arrow"></span>
                        </a>
                        <div class="collapse" id="sidebarProjects">
                            <ul class="side-nav-second-level">
 
                                <li>
                                    <a href="@Url.Action("ViewStockDeviceIT", "StockDeviceIT")?EmpNo=@Model.EmpNo&CodeId=@Model.CodeId">StockDeviceIT</a>

                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="content-page">
            <div class="content">
                @RenderBody()
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>
                                <script>document.write(new Date().getFullYear())</script> © YMTHOLDING & YMT-GROUP.COM
                            </h5>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/app")
    <script>
		window.baseUrl = "@baseurl";
		window.autherize = "@Url.Action("Login", "Account")";
		Icon = "@parthIcon";
    </script>

    <script src="~/Scripts/node_modules/moment/moment.js"></script>
    <script src="~/Scripts/node_modules/datetime-picker/jquery.datetimepicker.full.js"></script>
    <script src="~/Styles/HyperDEV/assets/js/vendor.min.js"></script>
    <script src="~/Styles/HyperDEV/assets/js/app.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

RfqEbr/1.UserInterface/EBR.Web/Views/Shared/_LayoutYMT.cshtml
@using EBR.Web.Services
@{
    var pathImages = Url.Content("~/Images/");
    var parthIcon = pathImages + "PraIcon.ico";
    var baseurl = Request.Url.GetLeftPart(UriPartial.Authority) + Url.Content("~");
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="X-UA-Compatible" content="IE=10; IE=9; IE=8; IE=7; IE=EDGE" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes">
    <title>YMT-GROUP</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">


    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <link rel="shortcut icon" href="~/Images/YMTHolding.png">

    <link href="~/Styles/HyperDEV/assets/css/vendor/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
    <link href="~/Styles/HyperDEV/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Styles/HyperDEV/assets/css/app.min.css" rel="stylesheet" type="text/css" id="app-style" />

</head>

<body class="loading" data-layout-color="light" data-layout="topnav" data-layout-mode="fluid" data-rightbar-onstart="true"
    ng-app="MainApp">
    <!-- Begin page -->
    <div class="wrapper" id="app">
        <div class="content-page">
            <div class="content">
                <!-- Topbar Start -->
                <div class="navbar-custom topnav-navbar">
                    <div class="container-fluid">

                        <!-- LOGO -->
                        <a href="#" class="topnav-logo">
                            <span class="topnav-logo-lg">
                                <img src="~/Images/YMTHolding.png" alt="" height="50">
                            </span>
                            <span class="topnav-logo-sm">
                                <img src="~/Images/YMTHolding.png" alt="" height="50">
                            </span>
                        </a>

                        <ul class="list-unstyled topbar-menu float-end mb-0">
                            <li class="dropdown notification-list">
                                <a class="nav-link dropdown-toggle arrow-none" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                    <i class="dripicons-view-apps noti-icon"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated dropdown-lg p-0">
                                    <div class="p-2">
                                        <div class="row g-0">
                                            <div class="col">
                                                <a class="dropdown-icon-item" href="@Url.Action("Login", "Home")">
                                                    <img src="~/Images/YMTHolding.png" alt="YMTGROUP">
                                                    <span>YMT LOGIN</span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="dropdown notification-list">
                                <a class="nav-link dropdown-toggle arrow-none" data-bs-toggle="dropdown" href="#" id="topbar-notifydrop" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="dripicons-bell noti-icon"></i>
                                    <span class="noti-icon-badge"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated dropdown-lg" aria-labelledby="topbar-notifydrop">

                                    <!-- item-->
                                    <div class="dropdown-item noti-title px-3">
                                        <h5 class="m-0">
                                            <span class="float-end">
                                                <a href="javascript: void(0);" class="text-dark">
                                                    <small>Clear All</small>
                                                </a>
                                            </span>Notification
                                        </h5>
                                    </div>

                                    <div class="px-3" style="max-height: 300px;" data-simplebar>

                                        <h5 class="text-muted font-13 fw-normal mt-0">Today</h5>
                                        <!-- item-->
                                        <a href="javascript:void(0);" class="dropdown-item p-0 notify-item card unread-noti shadow-none mb-2">
                                            <div class="card-body">
                                                <span class="float-end noti-close-btn text-muted"><i class="mdi mdi-close"></i></span>
                                                <div class="d-flex align-items-center">
                                                    <div class="flex-shrink-0">
                                                        <div class="notify-icon bg-primary">
                                                            <i class="mdi mdi-comment-account-outline"></i>
                                                        </div>
                                                    </div>
                                                    <div class="flex-grow-1 text-truncate ms-2">
                                                        <h5 class="noti-item-title fw-semibold font-14">Datacorp <small class="fw-normal text-muted ms-1">1 min ago</small></h5>
                                                        <small class="noti-item-subtitle text-muted">IT TEST DEV</small>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>

                                        <!-- item-->
                                        <a href="javascript:void(0);" class="dropdown-item p-0 notify-item card read-noti shadow-none mb-2">
                                            <div class="card-body">
                                                <span class="float-end noti-close-btn text-muted"><i class="mdi mdi-close"></i></span>
                                                <div class="d-flex align-items-center">
                                                    <div class="flex-shrink-0">
                                                        <div class="notify-icon bg-info">
                                                            <i class="mdi mdi-account-plus"></i>
                                                        </div>
                                                    </div>
                                                    <div class="flex-grow-1 text-truncate ms-2">
                                                        <h5 class="noti-item-title fw-semibold font-14">Admin <small class="fw-normal text-muted ms-1">1 hours ago</small></h5>
                                                        <small class="noti-item-subtitle text-muted">TEST 2</small>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>


                                        <div class="text-center">
                                            <i class="mdi mdi-dots-circle mdi-spin text-muted h3 mt-0"></i>
                                        </div>
                                    </div>

                                </div>
                            </li>

                        </ul>
                        <a class="navbar-toggle" data-bs-toggle="collapse" data-bs-target="#topnav-menu-content">
                            <div class="lines">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </a>                 
                    </div>
                </div>
                <div class="topnav">
                    <div class="container-fluid">
                        <nav class="navbar navbar-dark navbar-expand-lg topnav-menu">
                            <div class="collapse navbar-collapse" id="topnav-menu-content">
                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-dashboards" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="uil-dashboard me-1"></i>Home
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="topnav-dashboards">
                                        </div>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-apps" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="uil-apps me-1"></i>Apps <div class="arrow-down"></div>
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="topnav-apps">
                                            <a href="https://ymtholding.com/" class="dropdown-item">YMT HOLDING</a>
                                            <a href="https://b2b.ymtinnovation.com/" class="dropdown-item">B2B</a>
                                            <a href="https://ndsthai.co.th/" class="dropdown-item">NDS Thailand</a>
                                        </div>
                                    </li>
                                    
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-dashboards" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="uil-box me-1"></i>activity <div class="arrow-down"></div>
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="topnav-apps">
                                            <a href="#" class="dropdown-item">กิจกรรมงานกฐิน 2567</a>

                                          </div>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>

                <div class="container-fluid">
                    @RenderBody()
                </div>

            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <script>document.write(new Date().getFullYear())</script> © YMTHOLDING & YMT-GROUP.COM
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/addon")
    @Scripts.Render("~/bundles/app")

    <script>
		window.baseUrl = "@baseurl";
		window.autherize = "@Url.Action("Login", "Account")";
		Icon = "@parthIcon";
    </script>

    <!-- bundle -->
    <script src="~/Styles/HyperDEV/assets/js/vendor.min.js"></script>
    <script src="~/Styles/HyperDEV/assets/js/app.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

RfqEbr/1.UserInterface/EBR.Web/Views/Shared/_LoginLayoutNew.cshtml
@using EBR.Web.Services
@{
    var pathImages = Url.Content("~/Images/");
    var parthIcon = pathImages + "YMTHolding.png";
    var baseurl = Request.Url.GetLeftPart(UriPartial.Authority) + Url.Content("~");
}
<!DOCTYPE html>

<html ng-app="MainApp">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="X-UA-Compatible" content="IE=10; IE=9; IE=8; IE=7; IE=EDGE" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes">
    <title>YMT-GROUP</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="shortcut icon" href="~/Images/YMTHolding.png">

    <!-- Fontawesome -->
    <link href="~/Content/vendor/fortawesomes/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <!-- Notyf -->
    <link href="~/Content/vendor/notyf/notyf.min.css" rel="stylesheet" />
    <!-- Volt CSS -->
    <link href="~/Content/volt.css" rel="stylesheet" />
    <link href="~/Content/volt.css.map" rel="stylesheet" />

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>

<body class="bg-soft" ng-app="MainApp">
    <main>
        <section class="vh-lg-100 d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center form-bg-image">
                    @RenderBody()
                </div>
            </div>
        </section>
    </main>

    <script src="~/Content/js/sweetalert299.js"></script>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/app")

    <script>
        window.baseUrl = "@baseurl";
        window.autherize = "@Url.Action("Index", "Home")";
        Icon = "@parthIcon";
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>